### PR TITLE
Fixed wbi-toolbox working with Eigen 3.0.5

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
cc @jeljaik @francesco-romano ugly hack, but it was to get it working. Feel free to improve.

**Comment by francesco-romano** [comment]
What happens if instead of 
```
Eigen::Ref<Eigen::VectorXd> minLimits
```
you use
```
Eigen::VectorXd &minLimits
```
?

**Comment by traversaro** [comment]
I think it fails because you pass to the function two `Eigen::Map<Eigen::Matrix<real_T, Eigen::Dynamic, 1> >` elements. 
Just fixed the public members problem.

**Comment by francesco-romano** [comment]
+1

BTW: I think it was like it is now at the beginning. Then I changed it to use Ref. I don't remember why.

**Comment by traversaro** [comment]
@jeljaik  can we merge?

**Comment by rlober** [comment]
Thanks man!

**Pull request merged**
